version: "3.9"
networks:
  element-call_lkbackend:
    external: true
  traefik:
    external: true
  matrix-monitoring:
    external: true
services:
  # Jaeger
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:1.57
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jaeger.rule=Host(`jaeger.jefferson.tcc-engenharia.online`)"
      - "traefik.http.services.jaeger.loadbalancer.server.port=16686"
      - "traefik.http.routers.jaeger.entryPoints=web-secure"
      - "traefik.http.routers.jaeger.tls.certResolver=default"
      - "traefik.http.routers.jaeger.tls=true"
    ports:
      - "16686:16686" # Expose UI
      - "14268:14268" # Health Check
      - "14250:14250" # Collector HTTP
      - "4317:4317" # Collector HTTP
      - "4318:4318" # OTLP HTTP receiver
    networks:
      - "element-call_lkbackend"
      - "traefik"
      - "matrix-monitoring"
  # Collector
  collector-gateway:
    image: otel/opentelemetry-collector-contrib:0.102.1
    volumes:
      - ./collector-gateway.yaml:/etc/collector-gateway.yaml
    command: ["--config=/etc/collector-gateway.yaml"]
    ports:
      - "8889:8888" # prometheus
    networks:
      - "element-call_lkbackend"
      - "traefik"
      - "matrix-monitoring"
    depends_on:
      - jaeger-all-in-one
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.collector-gateway.rule=Host(`collector-gateway.jefferson.tcc-engenharia.online`)"
      - "traefik.http.services.collector-gateway.loadbalancer.server.port=4318"
      - "traefik.http.routers.collector-gateway.entryPoints=web-secure"
      - "traefik.http.routers.collector-gateway.tls.certResolver=default"
      - "traefik.http.routers.collector-gateway.tls=true"
      - "traefik.http.routers.collector-gateway.middlewares=https_redirect"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.https_redirect.redirectscheme.permanent=true"

  prometheus:
    image: quay.io/prometheus/prometheus:v2.52.0
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --enable-feature=otlp-write-receiver
      - --enable-feature=remote-write-receiver
      - --web.enable-remote-write-receiver
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - "element-call_lkbackend"
      - "traefik"
      - "matrix-monitoring"

  influxdb:
    image: influxdb:1.8
    environment:
      INFLUXDB_DB: metrics_call
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: jeffersoninfluxdbkey123
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb
    networks:
      - matrix-monitoring
      - traefik

  grafana:
    image: grafana/grafana:10.4.3
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - "element-call_lkbackend"
      - "traefik"
      - "matrix-monitoring"
    labels:
      - traefik.enable=true
      - traefik.http.routers.grafana.rule=Host(`grafana.jefferson.tcc-engenharia.online`)
      - traefik.http.services.grafana.loadbalancer.server.port=3000
      - traefik.http.routers.grafana.entryPoints=web-secure
      - traefik.http.routers.grafana.tls.certResolver=default
      - traefik.http.routers.grafana.tls=true

volumes:
  prometheus-data:
  influxdb-data:
  grafana-data:
