global:
  evaluation_interval: 30s
  scrape_interval: 5s
scrape_configs:
  - job_name: otel-collector
    static_configs:
      - targets:
          - "collector-gateway:8888"

remote_write:
  - url: "http://influxdb:8086/api/v1/prom/write?db=metrics_call&u=admin&p=jeffersoninfluxdbkey123"
